name: DoylCraft
version: ${project.version}
main: dev.siebrenvde.doylcraft.Main
api-version: 1.21
authors: [Siebrenvde]
depend: [LuckPerms, WorldGuard, DiscordSRV, Essentials, voicechat]
commands:
  pvp:
    description: Toggle PvP on or off