name: DoylCraft
version: ${project.version}
main: dev.siebrenvde.doylcraft.Main
api-version: 1.20
authors: [Siebrenvde]
depend: [LuckPerms, WorldGuard, DiscordSRV, Essentials]
commands:
  pvp:
    description: Toggle PvP on or off
  rank:
    aliases: [group]
    description: Change a players' group
  playtime:
    description: Get your time played
  streams:
    description: Get a list of online streamers
  getowner:
    description: Get the owner of an entity