name: DoylCraft
version: ${project.version}
main: dev.siebrenvde.doylcraft.Main
api-version: 1.13
authors: [Siebrenvde]
depend: [LuckPerms, WorldGuard, DiscordSRV, Essentials, TameableAxolotls]
commands:
  pvp:
    description: Toggle PvP on or off
  rank:
    aliases: [group]
    description: Change a players' group